name: Dockerize Python Application

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                 # Adjust this if your Dockerfile is in a different directory
          file: ./Dockerfile         # Specify the relative path to your Dockerfile if not in the root
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:latest # Change the tag as needed


