name: Deploy Infrastructure and Application to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: Akscluster-rsg
  LOCATION: uk south  # or your preferred Azure region
  BICEP_FILE_PATH: ./kubernetes/main.bicep  # Update this to your Bicep file path
  DOCKER_IMAGE_NAME: your-app-name
  DOCKER_FILE_PATH: Dockerfile

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ${{ env.BICEP_FILE_PATH }}
          failOnStdErr: false

  build-and-push:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure  
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to ACR
      - name: Log in to ACR
        run: |
          az acr login --name gtazureContainerRegistry

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:latest -f ${{ env.DOCKER_FILE_PATH }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:latest

      # Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      # Update Kubernetes manifests
      - name: Update Kubernetes manifests
        run: |
          sed -i 's|{{IMAGE_NAME}}|${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:latest|g' kubernetes/deployment.yaml

      # Deploy to AKS
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
          namespace: default

      # Azure Logout
      - name: Azure Logout
        run: |
          az logout
        if: always()
