name: Deploy Infrastructure and Application to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: Akscluster-rsg
  LOCATION: uk south
  BICEP_FILE_PATH: ./kubernetes/main.bicep
  DOCKER_IMAGE_NAME: your-app-name
  DOCKER_FILE_PATH: Dockerfile
  AKS_CLUSTER_NAME: GT-AKSCluster
  ACR_NAME: gtazureContainerRegistry

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ${{ env.BICEP_FILE_PATH }}
          failOnStdErr: false

  build-and-push:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} --registry ${{ env.ACR_NAME }} --file Dockerfile .
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Update Kubernetes manifests
        run: |
          sed -i 's|{{IMAGE_NAME}}|${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}|g' kubernetes/deployment.yaml
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
          namespace: default

      - name: Azure Logout
        run: |
          az logout
        if: always()
